light:
  - platform: mqtt
    name: "Dekala Table Lamp Color Light"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/color/state"
    command_topic: "tuya/dekala_table_lamp/color/state_set"
    brightness_state_topic: "tuya/dekala_table_lamp/color/brightness"
    brightness_command_topic: "tuya/dekala_table_lamp/color/brightness_set"
    brightness_scale: 1000
    hs_state_topic: "tuya/dekala_table_lamp/color/hs"
    hs_command_topic: "tuya/dekala_table_lamp/color/hs_set"

  - platform: mqtt
    name: "Dekala Table Lamp Night Light"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/night/state"
    command_topic: "tuya/dekala_table_lamp/night/state_set"
    brightness_state_topic: "tuya/dekala_table_lamp/night/brightness"
    brightness_command_topic: "tuya/dekala_table_lamp/night/brightness_set"
    brightness_scale: 1000

  - platform: mqtt
    name: "Dekala Table Lamp Effect Light"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/effect/state"
    command_topic: "tuya/dekala_table_lamp/effect/state_set"
    brightness_state_topic: "tuya/dekala_table_lamp/effect/brightness"
    brightness_command_topic: "tuya/dekala_table_lamp/effect/brightness_set"
    brightness_scale: 1000
    effect_state_topic: "tuya/dekala_table_lamp/effect/effect"
    effect_command_topic: "tuya/dekala_table_lamp/effect/effect_set"
    effect_list:
      - "Aurora Left"
      - "Aurora Right"
      - "Sunlight Sunset Orange"
      - "Sunlight Sunrise Pink"
      - "Night Red"
      - "Night Blue"
      - "Night Orange"
      - "Neon Clockwise"
      - "Neon Counterclockwise"
      - "Grassland GreenYellow"
      - "Grassland GreenWhite"
      - "Breath Red"
      - "Breath Purple"
      - "Breath Orange"
      - "Breath Yellow"
      - "Rainbow Up"
      - "Rainbow Down"
      - "Deep Sea RedBlueRed"
      - "Deep Sea WhiteBlueWhite"
      - "Bonfire Orange"
      - "Bonfire Red"

number:
  # EFFECT LIGHT
  - platform: mqtt
    name: "Dekala Table Lamp Effect Speed"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/effect/speed"
    command_topic: "tuya/dekala_table_lamp/effect/speed_set"
    min: 0
    max: 8
    step: 1

  # SLEEP AID
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Hours"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/hours"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/hours_set"
    min: 0
    max: 23
    step: 1
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Minutes"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/minutes"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/minutes_set"
    min: 0
    max: 59
    step: 1
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Duration"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/duration"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/duration_set"
    min: 1
    max: 30
    step: 1
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Light Advance Duration"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/light_advance_duration"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/light_advance_duration_set"
    min: 0
    max: 60
    step: 1

  # ALARM 1
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Hours"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/hours"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/hours_set"
    min: 0
    max: 23
    step: 1
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Minutes"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/minutes"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/minutes_set"
    min: 0
    max: 59
    step: 1
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Duration"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/duration"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/duration_set"
    min: 1
    max: 30
    step: 1

  # ALARM 2
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Hours"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/hours"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/hours_set"
    min: 0
    max: 23
    step: 1
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Minutes"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/minutes"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/minutes_set"
    min: 0
    max: 59
    step: 1
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Duration"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/duration"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/duration_set"
    min: 1
    max: 30
    step: 1

sensor:
  - platform: mqtt
    name: "Dekala table Lamp Alarms Status"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/status"

select:
  # SLEEP AID
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Light Type"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/light_type"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/light_type_set" 
    options: 
      - "None"
      - "Sleep Aid"
      - "Aurora"
      - "Sunlight"
      - "Night"
      - "Neon"
      - "Grassland"
      - "Breathing"
      - "Rainbow"
      - "Deep Sea"
      - "Bonfire"

  # ALARM 1
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Light Type"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/light_type"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/light_type_set" 
    options: 
      - "None"
      - "Wake Up"
      - "Aurora"
      - "Sunlight"
      - "Night"
      - "Neon"
      - "Grassland"
      - "Breathing"
      - "Rainbow"
      - "Deep Sea"
      - "Bonfire"

  # ALARM 2
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Light Type"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/light_type"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/light_type_set" 
    options: 
      - "None"
      - "Wake Up"
      - "Aurora"
      - "Sunlight"
      - "Night"
      - "Neon"
      - "Grassland"
      - "Breathing"
      - "Rainbow"
      - "Deep Sea"
      - "Bonfire"

switch:
  - platform: mqtt
    name: "Dekala Table Lamp Turn Off Alarms"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/status" # acknowledgement
    command_topic: "tuya/dekala_table_lamp/alarms/status_set"

  # SLEEP AID
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/state"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/state_set" 
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Sunday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/sun"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/sun_set"
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Monday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/mon"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/mon_set"
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Tuesday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/tue"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/tue_set"
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Wednesday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/wed"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/wed_set"
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Thursday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/thu"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/thu_set"
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Friday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/fri"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/fri_set"
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Saturday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/sat"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/sat_set"
  - platform: mqtt
    name: "Dekala Table Lamp Sleep Aid Auto Close"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/auto_close"
    command_topic: "tuya/dekala_table_lamp/alarms/sleep_aid/auto_close_set"

  # ALARM 1
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/state"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/state_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Sunday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/sun"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/sun_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Monday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/mon"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/mon_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Tuesday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/tue"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/tue_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Wednesday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/wed"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/wed_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Thursday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/thu"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/thu_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Friday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/fri"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/fri_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 1 Saturday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_1/sat"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_1/sat_set"

  # ALARM 2
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/state"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/state_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Sunday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/sun"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/sun_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Monday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/mon"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/mon_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Tuesday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/tue"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/tue_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Wednesday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/wed"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/wed_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Thursday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/thu"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/thu_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Friday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/fri"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/fri_set"
  - platform: mqtt
    name: "Dekala Table Lamp Alarm 2 Saturday"
    availability_topic: "tuya/dekala_table_lamp/LWT"
    state_topic: "tuya/dekala_table_lamp/alarms/alarm_2/sat"
    command_topic: "tuya/dekala_table_lamp/alarms/alarm_2/sat_set"